### ISSUE TITLE
Hello, I followed the instruction of installation, but when I installed, this plugin didn't work.

### ISSUE THREAD

**Issue by WuShichao** [slowphil/zotexmacs#2] opened 2016-10-09 08:32 UTC
Zotero returns:
    SERVER ERROR:
cannot connect with TeXmacs, or cannot login
try restarting TeXmacs or check config.

**Comment by WuShichao** [comment] 2016-10-09 08:34
I'm using it on deepin linux. And I have added the content of the file "place in my-init-texmacs.scm" in the file $TEXMACS_HOME_PATH/progs/my-init-texmacs.scm.

**Comment by WuShichao** [comment] 2016-10-09 08:36
The plugin has installed correctly, because I can see the plugin's icon in the Zotero's UI.

**Comment by slowphil** [comment] 2016-10-09 11:02
Dear WuShichao,

Sorry to hear it's not working well for you. Unfortunately, I don't have an immediate answer/solution for you.

One possibility is that you are running an outdated Texmacs version (Texmacs in Debian is really old, and i'm not sure zotexmacs would be compatible with that old version... Are Deepin linux packages more up-to-date?) Can you tell me which texmacs version you are runninng?

In any case, further information regarding your problem can be obtained by running texmacs from a terminal:

texmacs --debug-io

and report here what is displayed on the console.

Best,
Philippe

**Comment by WuShichao** [comment] 2016-10-09 14:47
My TeXmacs's version is 1.99.4. Here is the imformation in console:

Backtrace:
In /home/nightwing/.TeXmacs/progs/my-init-texmacs.scm:
   1: 0\* [display (quasiquote running) ...

/home/nightwing/.TeXmacs/progs/my-init-texmacs.scm:1:1: While evaluating arguments to display in expression (display (quasiquote #) my-init-texmacs\n ...):
/home/nightwing/.TeXmacs/progs/my-init-texmacs.scm:1:1: Unbound variable: my-init-texmacs\n
TeXmacs] With linked TrueType support

**Comment by slowphil** [comment] 2016-10-09 17:42
OK, I think I understand what's  happening. I guess you edited your my-init-texmacs file using texmacs itself and you simply used "paste". The result is that Texmacs tried to smartly "interpret" what you were pasting and somehow converted double quotes (") to ``. Just erase all of what you pasted and use "paste from... verbatim" (alternatively, use a plain text editor instead of texmacs). That should fix the issue. Let me know if you still experience a problem.

Best,
Philippe

**Comment by WuShichao** [comment] 2016-10-10 00:36
You are right, thank you! The reason of using TeXmacs to edit my-init-texmacs is that your zotexmacs doc.tm says I can find the my-init-texmacs in  Tools→Developper tools menu, but I ignored the following :"paste from… verbatim" (IMPORTANT: do not use plain "paste")....

Thank you!

**Comment by WuShichao** [comment] 2016-10-10 08:55
I have a new problem....TeXmacs can't work now, I run it in terminal, terminal returns these:

Backtrace:
In unknown file:
   ?: 21  [#<procedure #f #> "/usr/share/texmacs/TeXmacs/progs/kernel/texmacs/tm-dialogue.scm"]
   ?: 22  [with-fluid\* #<fluid 7> #f #<procedure #f ()>]
   ?: 23\* [#<procedure #f ()>]
   ?: 24\* [load-file #<procedure new-primitive-load #> ...]
   ?: 25\* [save-module-excursion #<procedure #f ()>]
   ?: 26  (let (# #) (dynamic-wind # thunk #))
   ?: 27  [dynamic-wind #<procedure #f ()> #<procedure #f ()> #<procedure #f ()>]
   ?: 28\* [#<procedure #f ()>]
   ?: 29\* [new-primitive-load "/usr/share/texmacs/TeXmacs/progs/kernel/texmacs/tm-dialogue.scm"]
In /usr/share/texmacs/TeXmacs/progs/init-texmacs.scm:
  56: 30  [with-fluid\* #<fluid 7> #<procedure new-read (port)> #<procedure #f ()>]
In unknown file:
   ?: 31\* [#<procedure #f ()>]
In /usr/share/texmacs/TeXmacs/progs/init-texmacs.scm:
  57: 32\* [primitive-load "/usr/share/texmacs/TeXmacs/progs/kernel/texmacs/tm-dialogue.scm"]
In /usr/share/texmacs/TeXmacs/progs/kernel/texmacs/tm-dialogue.scm:
 323: 33\* (on-entry (retrieve-learned))
 323: 34  (begin (retrieve-learned))
    ...
 318: 35  (let\* ((l #) (old? #) (decode #)) (set! interactive-arg-table (decode l)))
 318: 36\* [load-object "$TEXMACS_HOME_PATH/system/interactive.scm"]
In /usr/share/texmacs/TeXmacs/progs/kernel/boot/abbrevs.scm:
  79: 37  (let\* ((r (read #))) (if (eof-object? r) (quote ()) r))
  79: 38\* [new-read #<input: /home/nightwing/.TeXmacs/system/interactive.scm 19>]
In /usr/share/texmacs/TeXmacs/progs/init-texmacs.scm:
  35: 39  (let\* ((form #)) (if (and # #) (let\* # #)) form)
  35: 40\* [read #<input: /home/nightwing/.TeXmacs/system/interactive.scm 19>]

/usr/share/texmacs/TeXmacs/progs/init-texmacs.scm:35:15: In procedure scm_lreadr in expression (old-read port):
/usr/share/texmacs/TeXmacs/progs/init-texmacs.scm:35:15: /home/nightwing/.TeXmacs/system/interactive.scm:112:41: Unknown # object: #<
running my-init-texmacs
Backtrace:
In /home/nightwing/.TeXmacs/progs/my-init-texmacs.scm:
   3: 0\* (define-preferences ("zotero-server" #t noop))

/home/nightwing/.TeXmacs/progs/my-init-texmacs.scm:3:1: In expression (define-preferences ("zotero-server" #t noop)):
/home/nightwing/.TeXmacs/progs/my-init-texmacs.scm:3:1: Unbound variable: define-preferences
TeXmacs] With linked TrueType support
Backtrace:
In /usr/share/texmacs/TeXmacs/progs/init-buffer.scm:
  14: 0\* (when (buffer-newly-created? #) (use-modules # #) ...)
  14: 1  (if (buffer-newly-created? #) (begin # # # ...))
  14: 2\* (buffer-newly-created? (current-buffer))

/usr/share/texmacs/TeXmacs/progs/init-buffer.scm:14:7: In expression (buffer-newly-created? (current-buffer)):
/usr/share/texmacs/TeXmacs/progs/init-buffer.scm:14:7: Unbound variable: buffer-newly-created?

**Comment by WuShichao** [comment] 2016-10-10 09:10
I remove the .TeXmacs folder, then it works again.

**Comment by slowphil** [comment] 2016-10-10 16:09
Your last issue was caused by a file that got corrupted, and most likely erasing only the content of .TeXmacs/system would have been sufficient...
As for the initial issue, you had correctly followed the instructions! I fixed them (with the paste verbatim) only after understanding what had happened: when my-init-texmacs.scm does not exists, it is created, but it is initially considered as a standard TeXmacs document (instead of scheme code), that's why TeXmacs want to do its smart trick about quotes... 

Anyway I'm glad to see it's working now, and I close the issue.

**Closed as completed by slowphil** 2016-10-10 16:09 UTC
